### ISSUE TITLE
Editor scripts fail to compile on Unity 6000.6 — legacy UxmlFactory/UxmlTraits API removed

### ISSUE THREAD

**Issue by paochanz** [CyberAgentGameEntertainment/AudioConductor#25]
## Environment

- Unity 6000.6.0f1 (macOS, Apple Silicon)
- AudioConductor v2.5.0 (installed via git URL: `?path=/Packages/AudioConductor`)

## Problem

Unity 6000.6 removed the legacy UI Toolkit UXML factory API (`UxmlFactory<T, TTraits>`, `UxmlTraits`, `UxmlXxxAttributeDescription`, `IUxmlAttributes`). As a result, the `AudioConductor.Editor` assembly fails to compile with ~150 errors across 16 files, and the Editor can only open the project in Safe Mode.

Representative errors:

```
Editor/Foundation/PopupIntField.cs(13,40): error CS0308: The non-generic type 'PopupIntField.UxmlFactory' cannot be used with type arguments
Editor/Foundation/PopupIntField.cs(13,67): error CS0246: The type or namespace name 'UxmlTraits' could not be found
Editor/Core/Tools/CueSheetEditor/Views/CueInspectorView.cs(390,53): error CS0426: The type name 'UxmlTraits' does not exist in the type 'VisualElement'
Editor/Core/Tools/Shared/SliderAndFloatField.cs(123,30): error CS0246: The type or namespace name 'UxmlIntAttributeDescription' could not be found
```

## Steps to reproduce

1. Create a new Unity 6000.6.0f1 project
2. Add `jp.co.cyberagent.audioconductor` via git URL
3. Compilation fails; the Editor offers Safe Mode

## Reference migration (attached patch)

We migrated the 16 affected Editor files to the attribute-based API (`[UxmlElement]` / `[UxmlAttribute]`, available since Unity 2023.2) and confirmed the package compiles and the runtime works on 6000.6.0f1 (attached: `audioconductor_unity6006_migration.patch`). Notes:

- Classes with UXML factories became `partial` with `[UxmlElement]`
- `UxmlTraits.Init` attribute handling moved to `[UxmlAttribute]` property setters (existing kebab-case attribute names are preserved, so no `.uxml` changes were needed)
- `CuePlayTypeField` / `ThrottleTypeField` enum initialization moved from `Init()` to constructors

Since the package supports "Unity 2022.3 or higher", upstream would presumably need `#if UNITY_2023_2_OR_NEWER` dual paths to keep 2022.3 compatibility — we have not verified older versions, which is why we are filing an issue rather than a PR. Happy to open a PR based on this patch if that would help.

## 日本語要約

Unity 6000.6 で旧 UI Toolkit API(`UxmlFactory`/`UxmlTraits` 等)が削除されたため、AudioConductor v2.5.0 の Editor アセンブリがコンパイルできず、プロジェクトが Safe Mode でしか開けなくなります。当方で 16 ファイルを `[UxmlElement]`/`[UxmlAttribute]` ベースへ移行したパッチを添付します(6000.6.0f1 でコンパイル・動作確認済み。2022.3 系での検証は未実施)。必要であればこのパッチを元に PR を作成します。

<details>
<summary>Reference migration patch (16 files, against v2.5.0)</summary>

```diff
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueInspectorView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueInspectorView.cs
index 4d86033..3c41020 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueInspectorView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueInspectorView.cs
@@ -17,7 +17,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
-    internal sealed class CueInspectorView : VisualElement, IDisposable
+    [UxmlElement]
+    internal sealed partial class CueInspectorView : VisualElement, IDisposable
     {
         private readonly Subject<int> _categoryChangedSubject = new();
         private readonly PopupIntField _categoryField;
@@ -380,17 +381,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 
         #endregion
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<CueInspectorView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListEditorPaneView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListEditorPaneView.cs
index 0d5d9d6..8081634 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListEditorPaneView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListEditorPaneView.cs
@@ -15,7 +15,8 @@ using TwoPaneSplitView = AudioConductor.Editor.Core.Tools.Shared.TwoPaneSplitVie
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
-    internal sealed class CueListEditorPaneView : VisualElement, ICueListEditorPaneView
+    [UxmlElement]
+    internal sealed partial class CueListEditorPaneView : VisualElement, ICueListEditorPaneView
     {
         private readonly ToolbarToggle _inspectorToggle;
 
@@ -232,17 +233,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 
         #endregion
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<CueListEditorPaneView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListView.cs
index 0fe412c..c30f5f0 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueListView.cs
@@ -22,7 +22,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
-    internal sealed class CueListView : VisualElement, IDisposable
+    [UxmlElement]
+    internal sealed partial class CueListView : VisualElement, IDisposable
     {
         private readonly List<int> _addedItemIds = new();
         private readonly Subject<AssetAddOperationRequestedEvent> _assetAddOperationRequestedSubject = new();
@@ -222,17 +223,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 
         #endregion
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<CueListView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueSheetParameterPaneView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueSheetParameterPaneView.cs
index acc1feb..dafa8ce 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueSheetParameterPaneView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueSheetParameterPaneView.cs
@@ -13,7 +13,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
-    internal sealed class CueSheetParameterPaneView : VisualElement, IDisposable
+    [UxmlElement]
+    internal sealed partial class CueSheetParameterPaneView : VisualElement, IDisposable
     {
         private readonly Button _applyReferenceSampleRateButton;
         private readonly Subject<Empty> _applyReferenceSampleRateSubject = new();
@@ -218,17 +219,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 
         #endregion
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<CueSheetParameterPaneView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueTrackInspectorView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueTrackInspectorView.cs
index 659f576..b656037 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueTrackInspectorView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/CueTrackInspectorView.cs
@@ -10,7 +10,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
-    internal sealed class CueTrackInspectorView : VisualElement, IDisposable
+    [UxmlElement]
+    internal sealed partial class CueTrackInspectorView : VisualElement, IDisposable
     {
         public CueTrackInspectorView()
         {
@@ -32,17 +33,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
             this.SetDisplay(false);
         }
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<CueTrackInspectorView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/InspectorView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/InspectorView.cs
index 27c15e3..af3ca35 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/InspectorView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/InspectorView.cs
@@ -10,7 +10,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
-    internal sealed class InspectorView : VisualElement, IDisposable
+    [UxmlElement]
+    internal sealed partial class InspectorView : VisualElement, IDisposable
     {
         public InspectorView()
         {
@@ -28,17 +29,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
             // nothing
         }
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<InspectorView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/OtherOperationPaneView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/OtherOperationPaneView.cs
index eac61e2..dbcb997 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/OtherOperationPaneView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/OtherOperationPaneView.cs
@@ -11,7 +11,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
-    internal sealed class OtherOperationPaneView : VisualElement, IDisposable
+    [UxmlElement]
+    internal sealed partial class OtherOperationPaneView : VisualElement, IDisposable
     {
         private readonly Button _exportButton;
         private readonly Subject<Empty> _exportClickedSubject = new();
@@ -91,17 +92,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 
         #endregion
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<OtherOperationPaneView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/TrackInspectorView.cs b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/TrackInspectorView.cs
index 19904e2..aa2e101 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/TrackInspectorView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/CueSheetEditor/Views/TrackInspectorView.cs
@@ -17,6 +17,7 @@ using Object = UnityEngine.Object;
 
 namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 {
+    [UxmlElement]
     internal sealed partial class TrackInspectorView : VisualElement, IDisposable
     {
         private readonly Button _analyzeButton;
@@ -509,17 +510,5 @@ namespace AudioConductor.Editor.Core.Tools.CueSheetEditor.Views
 
         #endregion
 
-        #region Uxml
-
-        public new class UxmlFactory : UxmlFactory<TrackInspectorView, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-        }
-
-        #endregion
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/Shared/ColorDefinePopupField.cs b/Packages/AudioConductor/Editor/Core/Tools/Shared/ColorDefinePopupField.cs
index 61a2635..b207f2b 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/Shared/ColorDefinePopupField.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/Shared/ColorDefinePopupField.cs
@@ -8,7 +8,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.Shared
 {
-    internal sealed class ColorDefinePopupField : BindableElement, INotifyValueChanged<string?>
+    [UxmlElement]
+    internal sealed partial class ColorDefinePopupField : BindableElement, INotifyValueChanged<string?>
     {
         private readonly IMGUIContainer _imguiContainer = new();
         private readonly Label _label = new();
@@ -40,8 +41,11 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             _imguiContainer.style.flexGrow = 1;
 
             _imguiContainer.onGUIHandler = OnGUI;
+
+            label = "Label Name";
         }
 
+        [UxmlAttribute]
         public string label
         {
             get => _label.text;
@@ -81,22 +85,5 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             value = AudioConductorGUI.ColorDefine.Popup(_imguiContainer.contentRect, _value, showMixedValue) ?? _value;
         }
 
-        public new class UxmlFactory : UxmlFactory<ColorDefinePopupField, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-            private readonly UxmlStringAttributeDescription _label = new()
-                { name = "label", defaultValue = "Label Name" };
-
-            public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
-            {
-                base.Init(ve, bag, cc);
-                var container = (ColorDefinePopupField)ve;
-                container.label = _label.GetValueFromBag(bag, cc);
-            }
-        }
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/Shared/CuePlayTypeField.cs b/Packages/AudioConductor/Editor/Core/Tools/Shared/CuePlayTypeField.cs
index d67ab37..7df67aa 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/Shared/CuePlayTypeField.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/Shared/CuePlayTypeField.cs
@@ -9,21 +9,13 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.Shared
 {
-    internal sealed class CuePlayTypeField : EnumField
+    [UxmlElement]
+    internal sealed partial class CuePlayTypeField : EnumField
     {
-        public new class UxmlFactory : UxmlFactory<CuePlayTypeField, UxmlTraits>
+        public CuePlayTypeField()
         {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-            public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
-            {
-                base.Init(ve, bag, cc);
-                ((EnumField)ve).Init(CuePlayType.Sequential, false);
-                ((EnumField)ve).label = "Play Type";
-            }
+            Init(CuePlayType.Sequential, false);
+            label = "Play Type";
         }
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndFloatField.cs b/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndFloatField.cs
index e1bf97a..a1eb438 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndFloatField.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndFloatField.cs
@@ -9,7 +9,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.Shared
 {
-    internal sealed class SliderAndFloatField : VisualElement, INotifyValueChanged<float>
+    [UxmlElement]
+    internal sealed partial class SliderAndFloatField : VisualElement, INotifyValueChanged<float>
     {
         private readonly FloatField _float = new();
         private readonly Slider _slider = new();
@@ -41,20 +42,28 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             _float.style.marginRight = 0;
             _float.style.marginTop = 0;
             _float.style.marginBottom = 0;
+
+            label = "Label Name";
+            highValue = 100;
+            fieldWidth = 50;
+            isDelayed = true;
         }
 
+        [UxmlAttribute]
         public string label
         {
             get => _slider.label;
             set => _slider.label = value;
         }
 
+        [UxmlAttribute]
         public float lowValue
         {
             get => _slider.lowValue;
             set => _slider.lowValue = value;
         }
 
+        [UxmlAttribute]
         public float highValue
         {
             get => _slider.highValue;
@@ -67,6 +76,7 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             set => _slider.showMixedValue = _float.showMixedValue = value;
         }
 
+        [UxmlAttribute]
         public float value
         {
             get => _value;
@@ -90,6 +100,20 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             }
         }
 
+        [UxmlAttribute]
+        public int fieldWidth
+        {
+            get => (int)_float.resolvedStyle.width;
+            set => SetFieldWidth(value);
+        }
+
+        [UxmlAttribute]
+        public bool isDelayed
+        {
+            get => _float.isDelayed;
+            set => SetIsDelayed(value);
+        }
+
         public void SetValueWithoutNotify(float newValue)
         {
             _value = newValue;
@@ -113,39 +137,5 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             value = evt.newValue;
         }
 
-        public new class UxmlFactory : UxmlFactory<SliderAndFloatField, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-            private readonly UxmlIntAttributeDescription
-                _fieldWidth = new() { name = "field-width", defaultValue = 50 };
-
-            private readonly UxmlFloatAttributeDescription _highValue = new()
-                { name = "high-value", defaultValue = 100 };
-
-            private readonly UxmlBoolAttributeDescription _isDelayed = new()
-                { name = "is-delayed", defaultValue = true };
-
-            private readonly UxmlStringAttributeDescription _label = new()
-                { name = "label", defaultValue = "Label Name" };
-
-            private readonly UxmlFloatAttributeDescription _lowValue = new() { name = "low-value", defaultValue = 0 };
-            private readonly UxmlFloatAttributeDescription _value = new() { name = "value", defaultValue = 0 };
-
-            public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
-            {
-                base.Init(ve, bag, cc);
-                var container = (SliderAndFloatField)ve;
-                container.label = _label.GetValueFromBag(bag, cc);
-                container.lowValue = _lowValue.GetValueFromBag(bag, cc);
-                container.highValue = _highValue.GetValueFromBag(bag, cc);
-                container.value = _value.GetValueFromBag(bag, cc);
-                container.SetFieldWidth(_fieldWidth.GetValueFromBag(bag, cc));
-                container.SetIsDelayed(_isDelayed.GetValueFromBag(bag, cc));
-            }
-        }
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndIntegerField.cs b/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndIntegerField.cs
index 70166ce..3ebeb1d 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndIntegerField.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/Shared/SliderAndIntegerField.cs
@@ -9,7 +9,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.Shared
 {
-    internal sealed class SliderAndIntegerField : VisualElement, INotifyValueChanged<int>
+    [UxmlElement]
+    internal sealed partial class SliderAndIntegerField : VisualElement, INotifyValueChanged<int>
     {
         private readonly IntegerField _integer = new();
         private readonly SliderInt _slider = new();
@@ -41,20 +42,28 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             _integer.style.marginRight = 0;
             _integer.style.marginTop = 0;
             _integer.style.marginBottom = 0;
+
+            label = "Label Name";
+            highValue = 100;
+            fieldWidth = 70;
+            isDelayed = true;
         }
 
+        [UxmlAttribute]
         public string label
         {
             get => _slider.label;
             set => _slider.label = value;
         }
 
+        [UxmlAttribute]
         public int lowValue
         {
             get => _slider.lowValue;
             set => _slider.lowValue = value;
         }
 
+        [UxmlAttribute]
         public int highValue
         {
             get => _slider.highValue;
@@ -67,6 +76,7 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             set => _slider.showMixedValue = _integer.showMixedValue = value;
         }
 
+        [UxmlAttribute]
         public int value
         {
             get => _value;
@@ -90,6 +100,20 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             }
         }
 
+        [UxmlAttribute]
+        public int fieldWidth
+        {
+            get => (int)_integer.resolvedStyle.width;
+            set => SetFieldWidth(value);
+        }
+
+        [UxmlAttribute]
+        public bool isDelayed
+        {
+            get => _integer.isDelayed;
+            set => SetIsDelayed(value);
+        }
+
         public void SetValueWithoutNotify(int newValue)
         {
             _value = newValue;
@@ -113,38 +137,5 @@ namespace AudioConductor.Editor.Core.Tools.Shared
             value = evt.newValue;
         }
 
-        public new class UxmlFactory : UxmlFactory<SliderAndIntegerField, UxmlTraits>
-        {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-            private readonly UxmlIntAttributeDescription
-                _fieldWidth = new() { name = "field-width", defaultValue = 70 };
-
-            private readonly UxmlIntAttributeDescription _highValue = new() { name = "high-value", defaultValue = 100 };
-
-            private readonly UxmlBoolAttributeDescription _isDelayed = new()
-                { name = "is-delayed", defaultValue = true };
-
-            private readonly UxmlStringAttributeDescription _label = new()
-                { name = "label", defaultValue = "Label Name" };
-
-            private readonly UxmlIntAttributeDescription _lowValue = new() { name = "low-value", defaultValue = 0 };
-            private readonly UxmlIntAttributeDescription _value = new() { name = "value", defaultValue = 0 };
-
-            public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
-            {
-                base.Init(ve, bag, cc);
-                var container = (SliderAndIntegerField)ve;
-                container.label = _label.GetValueFromBag(bag, cc);
-                container.lowValue = _lowValue.GetValueFromBag(bag, cc);
-                container.highValue = _highValue.GetValueFromBag(bag, cc);
-                container.value = _value.GetValueFromBag(bag, cc);
-                container.SetFieldWidth(_fieldWidth.GetValueFromBag(bag, cc));
-                container.SetIsDelayed(_isDelayed.GetValueFromBag(bag, cc));
-            }
-        }
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/Shared/ThrottleTypeField.cs b/Packages/AudioConductor/Editor/Core/Tools/Shared/ThrottleTypeField.cs
index 0c50f94..92c1013 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/Shared/ThrottleTypeField.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/Shared/ThrottleTypeField.cs
@@ -9,21 +9,13 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.Shared
 {
-    internal sealed class ThrottleTypeField : EnumField
+    [UxmlElement]
+    internal sealed partial class ThrottleTypeField : EnumField
     {
-        public new class UxmlFactory : UxmlFactory<ThrottleTypeField, UxmlTraits>
+        public ThrottleTypeField()
         {
-            public override string uxmlNamespace => "Unity.UI.Builder";
-        }
-
-        public new class UxmlTraits : VisualElement.UxmlTraits
-        {
-            public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
-            {
-                base.Init(ve, bag, cc);
-                ((EnumField)ve).Init(ThrottleType.PriorityOrder, false);
-                ((EnumField)ve).label = "Throttle Type";
-            }
+            Init(ThrottleType.PriorityOrder, false);
+            label = "Throttle Type";
         }
     }
 }
diff --git a/Packages/AudioConductor/Editor/Core/Tools/Shared/TwoPaneSplitView.cs b/Packages/AudioConductor/Editor/Core/Tools/Shared/TwoPaneSplitView.cs
index 45e4254..90d5703 100644
--- a/Packages/AudioConductor/Editor/Core/Tools/Shared/TwoPaneSplitView.cs
+++ b/Packages/AudioConductor/Editor/Core/Tools/Shared/TwoPaneSplitView.cs
@@ -8,10 +8,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Core.Tools.Shared
 {
-    internal sealed class TwoPaneSplitView : UnityEngine.UIElements.TwoPaneSplitView
+    [UxmlElement]
+    internal sealed partial class TwoPaneSplitView : UnityEngine.UIElements.TwoPaneSplitView
     {
-        public new class UxmlFactory : UxmlFactory<TwoPaneSplitView, UxmlTraits>
-        {
-        }
     }
 }
diff --git a/Packages/AudioConductor/Editor/Foundation/HelpBox.cs b/Packages/AudioConductor/Editor/Foundation/HelpBox.cs
index a0896c8..f974861 100644
--- a/Packages/AudioConductor/Editor/Foundation/HelpBox.cs
+++ b/Packages/AudioConductor/Editor/Foundation/HelpBox.cs
@@ -8,10 +8,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Foundation
 {
-    public class HelpBox : UnityEngine.UIElements.HelpBox
+    [UxmlElement]
+    public partial class HelpBox : UnityEngine.UIElements.HelpBox
     {
-        public new class UxmlFactory : UxmlFactory<HelpBox, UxmlTraits>
-        {
-        }
     }
 }
diff --git a/Packages/AudioConductor/Editor/Foundation/PopupIntField.cs b/Packages/AudioConductor/Editor/Foundation/PopupIntField.cs
index 6af98f4..0f30dc9 100644
--- a/Packages/AudioConductor/Editor/Foundation/PopupIntField.cs
+++ b/Packages/AudioConductor/Editor/Foundation/PopupIntField.cs
@@ -8,10 +8,8 @@ using UnityEngine.UIElements;
 
 namespace AudioConductor.Editor.Foundation
 {
-    public class PopupIntField : PopupField<int>
+    [UxmlElement]
+    public partial class PopupIntField : PopupField<int>
     {
-        public new class UxmlFactory : UxmlFactory<PopupIntField, UxmlTraits>
-        {
-        }
     }
 }
```

</details>
